#!/usr/bin/env python3
"""
Galileo E5a / E5b transmitter for GNU Radio + UHD (Ettus B200-mini family).

Purpose
───────
Transmit ONE spectrally-correct Galileo E5 sideband — E5a (1176.45 MHz) or
E5b (1207.14 MHz) — as a QPSK(10) signal: the data component on I, the pilot
component on Q, both BPSK-modulated with the real 10.23 Mcps tiered ranging
codes from the Galileo OS SIS ICD (Issue 2.2, Nov 2025). This is a single
sideband, NOT the full E5 AltBOC(15,10); it reproduces the correct ~20 MHz
BPSK(10) main lobe of one E5 half.

⚠  RF SAFETY / LEGAL: E5a/E5b are live GNSS bands. Transmit ONLY into a
   shielded / conducted setup (cable + attenuators into a receiver or spectrum
   analyser) that you are LICENSED / AUTHORISED to use. Radiating a GNSS code
   over the air can jam or spoof real receivers and is illegal in most places.

Signal construction (per ICD §3)
────────────────────────────────
Each E5 sideband carries two orthogonal components at 10.23 Mcps:

    E5a-I  data channel  ┐                      E5b-I  data channel  ┐
    E5a-Q  pilot channel ┘ QPSK on I/Q          E5b-Q  pilot channel ┘

Every component is a *tiered* code: a length-10230 primary code, generated by
two 14-bit LFSRs (output = reg1 XOR reg2, register 1 seeded all-ones, register
2 per-code start value, both reset after 10230 chips), overlaid chip-by-epoch
with a secondary code:

    component      primary   secondary            tiered period
    E5a-I (data)   10230     CS201  (20 chip)      20 ms
    E5a-Q (pilot)  10230     CS100n (100 chip)     100 ms
    E5b-I (data)   10230     CS41   (4 chip)       4 ms
    E5b-Q (pilot)  10230     CS100(n+50) (100)     100 ms

The full repeating period of each sideband is therefore 100 ms (an integer
number of every component's tiered period). At 40.92 MS/s that is exactly
4 092 000 complex samples (~32 MB), precomputed once into /dev/shm and replayed
with blocks.file_source(repeat=True) — so the whole 100 ms tiered structure is
bit-exact and loops with no seam. No navigation data is modulated (data symbol
held constant) to give a clean, deterministic ranging spectrum.

The primary generator, secondary codes and code→component assignment are all
validated bit-exact against the ICD's published check values — the "Initial
Sequence" (first-24-chip) hex column of Tables 17–20, all 4×50 = 200 primary
codes — by --self-test.

How it streams fast on a Pi (same three levers as gps_l1ca_tx)
────────────────────────────────────────────────────────────
1. PRECOMPUTE + LOOP: build the 100 ms buffer once, DMA bytes at runtime.
2. sc8 OVER THE WIRE: otw_format=sc8 halves USB payload.
3. NO STATUS UPDATES MID-RUN: UHD fastpath/underflow logging disabled; silent
   after start() (status writes under load actually *cause* underflows).
master_clock_rate is pinned equal to the sample rate (1:1, no FPGA resampling),
so samples-per-chip and the loop length stay exact.

Live tuning (retune while transmitting, via paramkit.live)
──────────────────────────────────────────────────────────
    gain        → UHD set_gain            (instant)
    amplitude   → multiply_const_cc.set_k (instant baseband digital scale)
Band, SVID, carrier, sample rate and otw are fixed for a run (restart to change).

CLI
───
    gal_e5_tx.py --band E5a --svid 1 --power -30 --rf on
    gal_e5_tx.py --band E5b --svid 12
    gal_e5_tx.py --self-test        # verify codes vs ICD check values, no hardware
    gal_e5_tx.py --describe-params  # paramkit JSON schema for the GUI
"""
from __future__ import annotations

import os
import signal
import sys
import threading
import time

# UHD/GNU Radio must be quiet BEFORE the libraries load (they read these at
# import). The heavy imports live inside main(), so setting them here takes
# effect. A task env (configs/tasks.yaml) can still override any of them.
os.environ.setdefault("UHD_LOG_CONSOLE_LEVEL", "off")   # no UHD console logging
os.environ.setdefault("UHD_LOG_FASTPATH_DISABLE", "1")  # no "UUUU" underflow spam
os.environ.setdefault("GR_DONT_LOAD_PREFS", "1")        # skip slow pref scan

# paramkit is pure-Python and always importable (agent puts it on PYTHONPATH).
# NumPy and GNU Radio are imported lazily so --self-test / --describe-params run
# anywhere, including CI and dev boxes without a radio stack.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from paramkit import Script, PowerMap

# Stable calibration signal id. When a task sets SDR_CAL_SIGNAL_ID to this value the
# agent injects this unit's resolved calibration (SDR_CALIBRATION_FILE); calkit reads
# it and --power maps through the unit's MEASURED curve at its real operating plane
# (e.g. EIRP). Absent it, the script runs uncalibrated (relative gain only). See the
# agent's docs/calibration.md.
CAL_SIGNAL_ID = "gal_e5"


# ═══════════════════════════════════════════════════════════════════════════════
# RF chain limits — there is NO baked dBm power scale. Absolute --power (dBm) comes
# only from the unit's injected calibration; uncalibrated, the script runs on a
# relative gain (never invented power levels). GAIN_AT_MAX_DB is the safety ceiling.
# ═══════════════════════════════════════════════════════════════════════════════
GAIN_AT_MAX_DB = 89.75      # the gain that produced it; also the HARD ceiling the script commands

# Fixed baseband digital amplitude (0..1). NOT a user control and never a task
# parameter: the calibration is measured at THIS amplitude, so a unit calibrated at a
# different amplitude no longer matches. calkit detects that at load and runs
# UNCALIBRATED with a loud warning until it is re-calibrated here.
AMPLITUDE = 0.5

# Hardware TX-gain ceiling of the B200-mini (dB) — the physical maximum, distinct
# from GAIN_AT_MAX_DB. The (normally-commented) calibration gain knob uses it.
HW_MAX_GAIN_DB = 89.75



_PMAP = None


def power_map() -> PowerMap:
    """Active power map: the unit's injected calibration curve if present
    (SDR_CALIBRATION_FILE), else it runs uncalibrated — a relative gain only (no baked
    slope-1 behaviour). Cached, so build_script and main share one — and so --power's schema
    bounds match the real operating range (calibrated → e.g. EIRP; else the baked SDR-port
    range)."""
    global _PMAP
    if _PMAP is None:
        _PMAP = PowerMap.load(PowerMap.uncalibrated(0.0, GAIN_AT_MAX_DB, AMPLITUDE))
    return _PMAP


def gain_for_power(delivered_dbm: float) -> float:
    """TX gain (dB) for a requested delivered power, through the active calibration (the
    unit's measured curve when present, else the baked anchor). Every caller keeps working."""
    return power_map().gain_for_power(float(delivered_dbm))


def power_for_gain(gain_db: float) -> float:
    """Delivered power (dBm) an actual hardware gain produces, through the active map."""
    return power_map().power_for_gain(float(gain_db))


# ── Constants ─────────────────────────────────────────────────────────────────

E5A_HZ = 1176.45e6
E5B_HZ = 1207.14e6

CHIP_RATE_HZ = 10.23e6          # E5 component chip rate (BPSK(10) per component)
PRIMARY_LEN = 10230             # chips in an E5 primary code

# ── Fixed radio setup (NOT parameters) ──────────────────────────────────────────────
SAMP_RATE_HZ = 61.38e6          # 6 samples/chip at 10.23 Mcps (exact); master clock 1:1
OTW_FORMAT = "sc8"              # over-the-wire; halves USB load

# Filter: BPSK(10) is a sinc² with nulls every 10.23 MHz. --sidelobes n keeps the main
# lobe + n sidelobes (±(n+1)·10.23 MHz). At 61.38 MHz (±30.69) n=2 is the whole signal.
E5_NULL_HZ = 10.23e6
MAX_SIDELOBES = 2
SIDELOBE_PRESETS = {
    "Main lobe only (±10.23 MHz)": 0,
    "Main + 1 sidelobe (±20.46 MHz)": 1,
    "Main + 2 sidelobes (±30.69 MHz, ≈ full)": 2,
}

FREQUENCIES = {
    "Galileo E5a (1176.45 MHz)": E5A_HZ,
    "Galileo E5b (1207.14 MHz)": E5B_HZ,
}

# Register-1 feedback taps are identical within a band; register 2 differs.
# Taps (octal) per ICD Table 16. Register-1 start value is all-ones for every
# E5 component; register-2 start values are the per-code tables below.
TAPS = {
    "E5a-I": (0o40503, 0o50661),
    "E5a-Q": (0o40503, 0o50661),
    "E5b-I": (0o64021, 0o51445),
    "E5b-Q": (0o64021, 0o43143),
}

# ── Register-2 start values (octal), ICD Tables 17–20 (50 codes each) ──────────
E5AI_S2 = {1:0o30305, 2:0o14234, 3:0o27213, 4:0o20577, 5:0o23312, 6:0o33463, 7:0o15614, 8:0o12537, 9:0o01527, 10:0o30236, 11:0o27344, 12:0o07272, 13:0o36377, 14:0o17046, 15:0o06434, 16:0o15405, 17:0o24252, 18:0o11631, 19:0o24776, 20:0o00630, 21:0o11560, 22:0o17272, 23:0o27445, 24:0o31702, 25:0o13012, 26:0o14401, 27:0o34727, 28:0o22627, 29:0o30623, 30:0o27256, 31:0o01520, 32:0o14211, 33:0o31465, 34:0o22164, 35:0o33516, 36:0o02737, 37:0o21316, 38:0o35425, 39:0o35633, 40:0o24655, 41:0o14054, 42:0o27027, 43:0o06604, 44:0o31455, 45:0o34465, 46:0o25273, 47:0o20763, 48:0o31721, 49:0o17312, 50:0o13277}
E5AQ_S2 = {1:0o25652, 2:0o05142, 3:0o24723, 4:0o31751, 5:0o27366, 6:0o24660, 7:0o33655, 8:0o27450, 9:0o07626, 10:0o01705, 11:0o12717, 12:0o32122, 13:0o16075, 14:0o16644, 15:0o37556, 16:0o02477, 17:0o02265, 18:0o06430, 19:0o25046, 20:0o12735, 21:0o04262, 22:0o11230, 23:0o00037, 24:0o06137, 25:0o04312, 26:0o20606, 27:0o11162, 28:0o22252, 29:0o30533, 30:0o24614, 31:0o07767, 32:0o32705, 33:0o05052, 34:0o27553, 35:0o03711, 36:0o02041, 37:0o34775, 38:0o05274, 39:0o37356, 40:0o16205, 41:0o36270, 42:0o06600, 43:0o26773, 44:0o17375, 45:0o35267, 46:0o36255, 47:0o12044, 48:0o26442, 49:0o21621, 50:0o25411}
E5BI_S2 = {1:0o07220, 2:0o26047, 3:0o00252, 4:0o17166, 5:0o14161, 6:0o02540, 7:0o01537, 8:0o26023, 9:0o01725, 10:0o20637, 11:0o02364, 12:0o27731, 13:0o30640, 14:0o34174, 15:0o06464, 16:0o07676, 17:0o32231, 18:0o10353, 19:0o00755, 20:0o26077, 21:0o11644, 22:0o11537, 23:0o35115, 24:0o20452, 25:0o34645, 26:0o25664, 27:0o21403, 28:0o32253, 29:0o02337, 30:0o30777, 31:0o27122, 32:0o22377, 33:0o36175, 34:0o33075, 35:0o33151, 36:0o13134, 37:0o07433, 38:0o10216, 39:0o35466, 40:0o02533, 41:0o05351, 42:0o30121, 43:0o14010, 44:0o32576, 45:0o30326, 46:0o37433, 47:0o26022, 48:0o35770, 49:0o06670, 50:0o12017}
E5BQ_S2 = {1:0o03331, 2:0o06143, 3:0o25322, 4:0o23371, 5:0o00413, 6:0o36235, 7:0o17750, 8:0o04745, 9:0o13005, 10:0o37140, 11:0o30155, 12:0o20237, 13:0o03461, 14:0o31662, 15:0o27146, 16:0o05547, 17:0o02456, 18:0o30013, 19:0o00322, 20:0o10761, 21:0o26767, 22:0o36004, 23:0o30713, 24:0o07662, 25:0o21610, 26:0o20134, 27:0o11262, 28:0o10706, 29:0o34143, 30:0o11051, 31:0o25460, 32:0o17665, 33:0o32354, 34:0o21230, 35:0o20146, 36:0o11362, 37:0o37246, 38:0o16344, 39:0o15034, 40:0o25471, 41:0o25646, 42:0o22157, 43:0o04336, 44:0o16356, 45:0o04075, 46:0o02626, 47:0o11706, 48:0o37011, 49:0o27041, 50:0o31024}

S2_BY_COMPONENT = {
    "E5a-I": E5AI_S2, "E5a-Q": E5AQ_S2,
    "E5b-I": E5BI_S2, "E5b-Q": E5BQ_S2,
}

# ── Secondary codes (ICD Tables 22–24) ────────────────────────────────────────
# E5a-I: CS201 (20 chip, same for all SVIDs). E5b-I: CS41 (4 chip, all SVIDs).
# E5a-Q: CS100n (100 chip, SVID n). E5b-Q: CS100(n+50) (100 chip, SVID n).
CS201 = "842E9"        # 20-chip, hex MSB-first, first chip = leftmost bit
CS41 = "E"             # 4-chip
E5AQ_SEC = {
     1: "83F6F69D8F6E15411FB8C9B1C",  2: "66558BD3CE0C7792E83350525",
     3: "59A025A9C1AF0651B779A8381",  4: "D3A32640782F7B18E4DF754B7",
     5: "B91FCAD7760C218FA59348A93",  6: "BAC77E933A779140F094FBF98",
     7: "537785DE280927C6B58BA6776",  8: "EFCAB4B65F38531ECA22257E2",
     9: "79F8CAE838475EA5584BEFC9B", 10: "CA5170FEA3A810EC606B66494",
    11: "1FC32410652A2C49BD845E567", 12: "FE0A9A7AFDAC44E42CB95D261",
    13: "B03062DC2B71995D5AD8B7DBE", 14: "F6C398993F598E2DF4235D3D5",
    15: "1BB2FB8B5BF24395C2EF3C5A1", 16: "2F920687D238CC7046EF6AFC9",
    17: "34163886FC4ED7F2A92EFDBB8", 18: "66A872CE47833FB2DFD5625AD",
    19: "99D5A70162C920A4BB9DE1CA8", 20: "81D71BD6E069A7ACCBEDC66CA",
    21: "A654524074A9E6780DB9D3EC6", 22: "C3396A101BEDAF623CFC5BB37",
    23: "C3D4AB211DF36F2111F2141CD", 24: "3DFF25EAE761739265AF145C1",
    25: "994909E0757D70CDE389102B5", 26: "B938535522D119F40C25FDAEC",
    27: "C71AB549C0491537026B390B7", 28: "0CDB8C9E7B53F55F5B0A0597B",
    29: "61C5FA252F1AF81144766494F", 30: "626027778FD3C6BB4BAA7A59D",
    31: "E745412FF53DEBD03F1C9A633", 32: "3592AC083F3175FA724639098",
    33: "52284D941C3DCAF2721DDB1FD", 34: "73B3D8F0AD55DF4FE814ED890",
    35: "94BF16C83BD7462F6498E0282", 36: "A8C3DE1AC668089B0B45B3579",
    37: "E23FFC2DD2C14388AD8D6BEC8", 38: "F2AC871CDF89DDC06B5960D2B",
    39: "06191EC1F622A77A526868BA1", 40: "22D6E2A768E5F35FFC8E01796",
    41: "25310A06675EB271F2A09EA1D", 42: "9F7993C621D4BEC81A0535703",
    43: "D62999EACF1C99083C0B4A417", 44: "F665A7EA441BAA4EA0D01078C",
    45: "46F3D3043F24CDEABD6F79543", 46: "E2E3E8254616BD96CEFCA651A",
    47: "E548231A82F9A01A19DB5E1B2", 48: "265C7F90A16F49EDE2AA706C8",
    49: "364A3A9EB0F0481DA0199D7EA", 50: "9810A7A898961263A0F749F56",
}
E5BQ_SEC = {
     1: "CFF914EE3C6126A49FD5E5C94",  2: "FC317C9A9BF8C6038B5CADAB3",
     3: "A2EAD74B6F9866E414393F239",  4: "72F2B1180FA6B802CB84DF997",
     5: "13E3AE93BC52391D09E84A982",  6: "77C04202B91B22C6D3469768E",
     7: "FEBC592DD7C69AB103D0BB29C",  8: "0B494077E7C66FB6C51942A77",
     9: "DD0E321837A3D52169B7B577C", 10: "43DEA90EA6C483E7990C3223F",
    11: "0366AB33F0167B6FA979DAE18", 12: "99CCBBFAB1242CBE31E1BD52D",
    13: "A3466923CEFDF451EC0FCED22", 14: "1A5271F22A6F9A8D76E79B7F0",
    15: "3204A6BB91B49D1A2D3857960", 16: "32F83ADD43B599CBFB8628E5B",
    17: "3871FB0D89DB77553EB613CC1", 18: "6A3CBDFF2D64D17E02773C645",
    19: "2BCD09889A1D7FC219F2EDE3B", 20: "3E49467F4D4280B9942CD6F8C",
    21: "658E336DCFD9809F86D54A501", 22: "ED4284F345170CF77268C8584",
    23: "29ECCE910D832CAF15E3DF5D1", 24: "456CCF7FE9353D50E87A708FA",
    25: "FB757CC9E18CBC02BF1B84B9A", 26: "5686229A8D98224BC426BC7FC",
    27: "700A2D325EA14C4B7B7AA8338", 28: "1210A330B4D3B507D854CBA3F",
    29: "438EE410BD2F7DBCDD85565BA", 30: "4B9764CC455AE1F61F7DA432B",
    31: "BF1F45FDDA3594ACF3C4CC806", 32: "DA425440FE8F6E2C11B8EC1A4",
    33: "EE2C8057A7C16999AFA33FED1", 34: "2C8BD7D8395C61DFA96243491",
    35: "391E4BB6BC43E98150CDDCADA", 36: "399F72A9EADB42C90C3ECF7F0",
    37: "93031FDEA588F88E83951270C", 38: "BA8061462D873705E95D5CB37",
    39: "D24188F88544EB121E963FD34", 40: "D5F6A8BB081D8F383825A4DCA",
    41: "0FA4A205F0D76088D08EAF267", 42: "272E909FAEBC65215E263E258",
    43: "3370F35A674922828465FC816", 44: "54EF96116D4A0C8DB0E07101F",
    45: "DE347C7B27FADC48EF1826A2B", 46: "01B16ECA6FC343AE08C5B8944",
    47: "1854DB743500EE94D8FC768ED", 48: "28E40C684C87370CD0597FAB4",
    49: "5E42C19717093353BCAAF4033", 50: "64310BAD8EB5B36E38646AF01",
}

# Per-band component / carrier / secondary-code layout.
BANDS = {
    "E5a": {
        "freq": E5A_HZ, "data": "E5a-I", "pilot": "E5a-Q",
        "sec_data": lambda svid: (CS201, 20),
        "sec_pilot": lambda svid: (E5AQ_SEC[svid], 100),
    },
    "E5b": {
        "freq": E5B_HZ, "data": "E5b-I", "pilot": "E5b-Q",
        "sec_data": lambda svid: (CS41, 4),
        "sec_pilot": lambda svid: (E5BQ_SEC[svid], 100),
    },
}

TIERED_PERIOD_MS = 100          # LCM of every component's tiered period
EPOCHS_PER_LOOP = TIERED_PERIOD_MS   # one primary epoch = 1 ms = 10230 chips


# ── Code generation (pure Python, no NumPy) ────────────────────────────────────

def _taps_vector(oct_val: int) -> list[int]:
    """Feedback-tap vector a_{i,j} for j=1..14 from octal notation (ICD §3.4.1):
    bits counted right-to-left from LSB j=0; return j=1..R (a_0 unused, a_R=1)."""
    return [(oct_val >> j) & 1 for j in range(1, 15)]


def _start_vector(oct_val: int) -> list[int]:
    """Register start-value vector s_{i,j} for j=1..14 from octal notation:
    bits counted right-to-left from LSB starting at j=1 (ICD §3.4.1)."""
    return [(oct_val >> (j - 1)) & 1 for j in range(1, 15)]


def primary_code(component: str, svid: int) -> list[int]:
    """Return the 10230-chip Galileo E5 primary code for a component
    ('E5a-I'|'E5a-Q'|'E5b-I'|'E5b-Q') and SVID (1..50), as a list of 0/1.

    Two 14-bit LFSRs: base register 1 seeded all-ones, base register 2 seeded
    with the per-code start value. Output chip = reg1[14] XOR reg2[14]; the new
    bit shifts into cell 1 (feedback = XOR of tapped cells). Registers are reset
    after 10230 chips (truncation to primary length)."""
    if not 1 <= svid <= 50:
        raise ValueError(f"SVID must be 1..50, got {svid}")
    t1_oct, t2_oct = TAPS[component]
    tap1, tap2 = _taps_vector(t1_oct), _taps_vector(t2_oct)
    c1 = [1] * 14
    c2 = _start_vector(S2_BY_COMPONENT[component][svid])
    out: list[int] = []
    for _ in range(PRIMARY_LEN):
        out.append(c1[13] ^ c2[13])
        fb1 = 0
        fb2 = 0
        for j in range(14):
            fb1 ^= tap1[j] & c1[j]
            fb2 ^= tap2[j] & c2[j]
        c1 = [fb1] + c1[:13]
        c2 = [fb2] + c2[:13]
    return out


def _hex_bits(hexstr: str, length: int) -> list[int]:
    """Hex code sequence → list of 0/1, MSB-first, first chip = leftmost bit
    (ICD §3.4.1.1 / §3.5.1 convention), truncated to `length` chips."""
    nbits = len(hexstr) * 4
    v = int(hexstr, 16)
    bits = [(v >> (nbits - 1 - i)) & 1 for i in range(nbits)]
    return bits[:length]


def secondary_code(band: str, channel: str, svid: int) -> list[int]:
    """Secondary (overlay) code for a band ('E5a'|'E5b'), channel
    ('data'|'pilot') and SVID, as a list of 0/1."""
    hexstr, length = BANDS[band]["sec_data" if channel == "data" else "sec_pilot"](svid)
    return _hex_bits(hexstr, length)


# ── Self-test: validate every code against the ICD's check values ──────────────

def _self_test() -> int:
    """Verify primary_code() against the ICD's published 'Initial Sequence'
    (first-24-chip hex) column for all 4 components × 50 codes, and the
    secondary code lengths/assignment. Returns 0 on success."""
    # First-24-chip hex check values, ICD Tables 17–20 ('Initial Sequence').
    chk = {
     "E5a-I": {1:0x3CEA9D, 2:0x9D8CF1, 3:0x45D1C8, 4:0x7A0133, 5:0x64D423, 6:0x23300D, 7:0x91CEF2, 8:0xAA82DC, 9:0xF2A17D, 10:0x3D84AE, 11:0x446D38, 12:0xC514F2, 13:0x0C0184, 14:0x8767E0, 15:0xCB8EFF, 16:0x93EBCD, 17:0x5D55CE, 18:0xB19B7C, 19:0x5805FC, 20:0xF99EA1, 21:0xB23CE5, 22:0x8515E8, 23:0x436822, 24:0x30F77B, 25:0xA7D629, 26:0x9BFAC7, 27:0x18A25B, 28:0x69A39F, 29:0x39B27D, 30:0x454598, 31:0xF2BC62, 32:0x9DDBC6, 33:0x332827, 34:0x6E2FCA, 35:0x22C6D5, 36:0xE881D9, 37:0x74C4DB, 38:0x13AB03, 39:0x119323, 40:0x594886, 41:0x9F4D89, 42:0x47A3C0, 43:0xC9ED53, 44:0x334994, 45:0x1B2A30, 46:0x5513F3, 47:0x7831C1, 48:0x30B93A, 49:0x84D5B4, 50:0xA5029C},
     "E5a-Q": {1:0x515537, 2:0xD67539, 3:0x58B2E5, 4:0x305914, 5:0x442710, 6:0x593CF8, 7:0x214AD7, 8:0x435EA6, 9:0xC1A7D5, 10:0xF0E94A, 11:0xA8C239, 12:0x2EB63B, 13:0x8F0A46, 14:0x896DD4, 15:0x0245F1, 16:0xEB0160, 17:0xED28B3, 18:0xCB9F5B, 19:0x576592, 20:0xA88811, 21:0xDD3649, 22:0xB59F42, 23:0xFF81F6, 24:0xCE8128, 25:0xDCD55C, 26:0x79E450, 27:0xB63460, 28:0x6D562B, 29:0x3A9010, 30:0x59CD72, 31:0xC0211A, 32:0x28EB96, 33:0xD7554B, 34:0x425126, 35:0xE0DAFB, 36:0xEF79F2, 37:0x18085D, 38:0xD50CD8, 39:0x0447B9, 40:0x8DE877, 41:0x0D1FA0, 42:0xC9FCF7, 43:0x48116D, 44:0x840BCC, 45:0x152004, 46:0x0D4897, 47:0xAF6D25, 48:0x4B7593, 49:0x71BB1B, 50:0x53DA0E},
     "E5b-I": {1:0xC5BEA1, 2:0x4F6248, 3:0xFD5488, 4:0x86277B, 5:0x9E39D5, 6:0xEA7EDE, 7:0xF28321, 8:0x4FB0C9, 9:0xF0AB64, 10:0x79833B, 11:0xEC2D91, 12:0x409B11, 13:0x397E16, 14:0x1E0FCD, 15:0xCB2F5A, 16:0xC1079A, 17:0x2D9BC6, 18:0xBC5146, 19:0xF848B0, 20:0x4F01E8, 21:0xB16C9B, 22:0xB2827D, 23:0x16C809, 24:0x7B570F, 25:0x1969C0, 26:0x512FA9, 27:0x73F36B, 28:0x2D5317, 29:0xEC8390, 30:0x380374, 31:0x46B4DE, 32:0x6C01D9, 33:0x0E0BB6, 34:0x2708C7, 35:0x265B55, 36:0xA68E1C, 37:0xC3916E, 38:0xBDC595, 39:0x1327D0, 40:0xEA921F, 41:0xD45869, 42:0x3EB98A, 43:0x9FDE16, 44:0x2A04CA, 45:0x3CA56F, 46:0x03928A, 47:0x4FB5B9, 48:0x101EC7, 49:0xC91D4F, 50:0xAFC22B},
     "E5b-Q": {1:0xE49AF0, 2:0xCE701F, 3:0x54B709, 4:0x641AB1, 5:0xFBD0AE, 6:0x0D8BC9, 7:0x805FA5, 8:0xD86BA0, 9:0xA7E921, 10:0x067E55, 11:0x3E4B58, 12:0x7D82FB, 13:0xE33BC2, 14:0x31372C, 15:0x46676F, 16:0xD2613E, 17:0xEB443C, 18:0x3FD0B1, 19:0xFCB7CF, 20:0xB83815, 21:0x48224A, 22:0x0FEE25, 23:0x38D33B, 24:0xC135B9, 25:0x71DE13, 26:0x7E8CFB, 27:0xB536C3, 28:0xB8E68C, 29:0x1E7272, 30:0xB75B69, 31:0x533F65, 32:0x812B41, 33:0x2C4DE1, 34:0x759E2C, 35:0x7E6434, 36:0xB43640, 37:0x05671B, 38:0x8C6FE0, 39:0x978D4E, 40:0x5319BF, 41:0x516499, 42:0x6E4292, 43:0xDC86A3, 44:0x8C46BE, 45:0xDF0B03, 46:0xE9A5B2, 47:0xB0E553, 48:0x07DBAC, 49:0x4778E4, 50:0x37AF4F},
    }
    ok = True
    for comp in ("E5a-I", "E5a-Q", "E5b-I", "E5b-Q"):
        good = 0
        for svid in range(1, 51):
            code = primary_code(comp, svid)
            first24 = 0
            for b in code[:24]:
                first24 = (first24 << 1) | b
            if len(code) == PRIMARY_LEN and first24 == chk[comp][svid]:
                good += 1
        comp_ok = good == 50
        ok = ok and comp_ok
        print(f"{comp}: {good}/50 primary codes match ICD first-24-chip check "
              f"[{'OK' if comp_ok else 'FAIL'}]")

    # Secondary codes: length + fixed-pattern sanity.
    cs201 = _hex_bits(CS201, 20)
    cs41 = _hex_bits(CS41, 4)
    sec_ok = (len(cs201) == 20 and len(cs41) == 4
              and cs41 == [1, 1, 1, 0]                     # CS41 hex 'E'
              and len(secondary_code("E5a", "pilot", 1)) == 100
              and len(secondary_code("E5b", "pilot", 50)) == 100)
    ok = ok and sec_ok
    print(f"secondaries: CS201 len={len(cs201)}, CS41={cs41}, "
          f"E5a-Q/E5b-Q len=100 [{'OK' if sec_ok else 'FAIL'}]")

    try:
        import numpy as np
    except ImportError:
        print("(numpy absent — skipping the filter check)")
        return 0 if ok else 1

    base, n, _ = build_iq_buffer("E5a", 1)

    def band(x, lo, hi):
        X = np.fft.fftshift(np.fft.fft(x))
        f = np.fft.fftshift(np.fft.fftfreq(len(x), 1.0 / SAMP_RATE_HZ))
        return float(np.sum(np.abs(X[(np.abs(f) >= lo) & (np.abs(f) < hi)]) ** 2))

    filt, taps, fp = filter_buffer(base, sidelobes=1, trans_hz=1.0e6)
    main = 10 * np.log10(band(filt, 0, E5_NULL_HZ) / band(base, 0, E5_NULL_HZ))
    kept = 10 * np.log10(band(filt, E5_NULL_HZ, 2 * E5_NULL_HZ)
                         / band(base, E5_NULL_HZ, 2 * E5_NULL_HZ))
    cut = 10 * np.log10(band(filt, 24e6, 30e6) / max(band(base, 24e6, 30e6), 1e-30))
    peak = float(np.max(np.abs(filt)))
    f_ok = abs(main) < 0.1 and abs(kept) < 0.1 and cut < -40 and peak * AMPLITUDE < 1.0
    print(f"filter (main+1 sidelobe, {taps} taps): main lobe {main:+.3f} dB, kept sidelobe "
          f"{kept:+.3f} dB, far sidelobe {cut:.0f} dB, peak×amp {peak*AMPLITUDE:.2f} "
          f"[{'OK' if f_ok else 'FAIL'}]")
    ok = ok and f_ok
    print("ALL E5 CHECKS PASSED" if ok else "SELF-TEST FAILED")
    return 0 if ok else 1


# ── Baseband buffer (one seamless-looping 100 ms tiered period) ────────────────

def build_iq_buffer(band: str, svid: int):
    """Build a complex64 baseband buffer holding a whole number of 100 ms E5 tiered
    periods that is also an exact integer number of samples at the fixed SAMP_RATE_HZ,
    so it loops with no seam. I = data component, Q = pilot component (QPSK), both ±1
    BPSK chips at 10.23 Mcps. No nav data (data symbol held constant → clean ranging
    spectrum). Constant modulus; amplitude is applied live downstream.

    Returns (iq: np.ndarray[complex64], n_samples: int, n_periods: int).
    """
    import numpy as np
    from fractions import Fraction

    sr = int(round(SAMP_RATE_HZ))
    cr = int(round(CHIP_RATE_HZ))
    chips_per_loop = PRIMARY_LEN * EPOCHS_PER_LOOP        # 10230 * 100 = 1_023_000

    # Samples for one 100 ms period as an exact fraction; tile by its denominator
    # to reach an integer sample count that still spans whole tiered periods.
    spp = Fraction(sr * chips_per_loop, cr)
    n_periods = spp.denominator
    n_samples = spp.numerator

    conf = BANDS[band]

    def tiered_chips(component: str, channel: str) -> "np.ndarray":
        prim = np.asarray(primary_code(component, svid), dtype=np.int8)  # (10230,)
        sec = np.asarray(secondary_code(band, channel, svid), dtype=np.int8)
        ns = len(sec)
        # secondary chip for each of the EPOCHS_PER_LOOP primary epochs
        overlay = sec[np.arange(EPOCHS_PER_LOOP) % ns]                    # (100,)
        chips = prim[None, :] ^ overlay[:, None]                         # (100,10230)
        return chips.reshape(-1)                                          # (1_023_000,)

    data_chips = tiered_chips(conf["data"], "data")
    pilot_chips = tiered_chips(conf["pilot"], "pilot")

    # One 100 ms period tiled n_periods times → chips_per_loop*n_periods chips.
    if n_periods > 1:
        data_chips = np.tile(data_chips, n_periods)
        pilot_chips = np.tile(pilot_chips, n_periods)

    total_chips = chips_per_loop * n_periods
    i_bip = (1.0 - 2.0 * data_chips).astype(np.float32)     # 0→+1, 1→−1
    q_bip = (1.0 - 2.0 * pilot_chips).astype(np.float32)

    # Zero-order-hold chip → sample (exact integer mapping over the whole loop).
    n = np.arange(n_samples, dtype=np.int64)
    chip_idx = (n * cr) // sr                               # 0..total_chips-1
    inv_sqrt2 = np.float32(1.0 / np.sqrt(2.0))
    iq = np.empty(n_samples, dtype=np.complex64)
    iq.real = i_bip[chip_idx] * inv_sqrt2                   # QPSK, |iq| = 1
    iq.imag = q_bip[chip_idx] * inv_sqrt2
    return iq, n_samples, n_periods


# ── Digital passband filter (unity gain, circular → loop-preserving) ────────────────

def _design_lowpass(fc_hz: float, trans_hz: float, max_taps: int):
    """Blackman-Harris windowed-sinc lowpass, UNITY passband gain. `fc_hz` is the −6 dB
    cutoff; `trans_hz` sets the tap count (steeper skirt → more taps). Returns (h, n_taps)."""
    import numpy as np
    m = int(np.ceil(5.5 * SAMP_RATE_HZ / max(trans_hz, 1.0))) | 1     # odd
    m = min(m, (max_taps | 1))
    k = np.arange(m)
    c = (m - 1) / 2.0
    fcn = min(fc_hz / SAMP_RATE_HZ, 0.499)          # never above Nyquist
    h = 2 * fcn * np.sinc(2 * fcn * (k - c))
    n1 = m - 1
    win = (0.35875 - 0.48829 * np.cos(2 * np.pi * k / n1)
           + 0.14128 * np.cos(4 * np.pi * k / n1) - 0.01168 * np.cos(6 * np.pi * k / n1))
    h = h * win
    h = h / h.sum()                                 # unity DC (→ passband) gain
    return h.astype(np.float64), m


def filter_buffer(base_iq, sidelobes: int, trans_hz: float):
    """Circularly filter the looped E5 buffer to keep the main lobe + `sidelobes` sidelobes
    (±(n+1)·10.23 MHz). Circular convolution keeps the result exactly periodic (seam-free
    loop); unity passband gain leaves the kept lobes' power unchanged. Returns
    (filtered_iq, n_taps, passband_edge_hz)."""
    import numpy as np
    fp = (int(sidelobes) + 1) * E5_NULL_HZ
    fc = fp + trans_hz / 2.0
    n = len(base_iq)
    h, m = _design_lowpass(fc, trans_hz, n // 2)
    filtered = np.fft.ifft(np.fft.fft(base_iq) * np.fft.fft(h, n)).astype(np.complex64)
    return filtered, m, fp


# ── Flowgraph ──────────────────────────────────────────────────────────────────

def _build_top_block(iq_path: str, center_freq_hz: float, gain_db: float, amplitude: float):
    """Construct the GNU Radio top_block. Imported lazily so the module loads
    without a radio stack for --self-test / --describe-params."""
    from gnuradio import gr, blocks, uhd

    class E5Tx(gr.top_block):
        def __init__(self):
            super().__init__("Galileo E5 TX")

            # Pin master clock == sample rate → 1:1, no FPGA resampling/coercion.
            args = (f"master_clock_rate={SAMP_RATE_HZ:.0f},"
                    "num_send_frames=512,send_frame_size=16000")
            self.usrp = uhd.usrp_sink(
                args,
                uhd.stream_args(cpu_format="fc32", otw_format=OTW_FORMAT, channels=[0]),
            )
            self.usrp.set_samp_rate(SAMP_RATE_HZ)
            self.usrp.set_center_freq(uhd.tune_request(center_freq_hz), 0)
            self.usrp.set_gain(gain_db, 0)

            self.src = blocks.file_source(gr.sizeof_gr_complex, iq_path, repeat=True)
            self.amp = blocks.multiply_const_cc(amplitude)
            self.connect(self.src, self.amp, self.usrp)

        # ── live setters (called from the main loop, device-safe) ──────────────
        def set_amplitude(self, a: float) -> None:
            self.amp.set_k(a)

        def set_gain(self, g: float) -> None:
            self.usrp.set_gain(g, 0)

        def swap_file(self, path: str) -> None:
            self.src.open(path, True)               # switch at the next work boundary

        def actual_gain(self) -> float:
            return self.usrp.get_gain(0)

        def actual_samp_rate(self) -> float:
            return self.usrp.get_samp_rate()

    return E5Tx()


# ── Parameter schema ────────────────────────────────────────────────────────────

def build_script() -> Script:
    return (
        Script("Galileo E5a / E5b single-sideband transmitter (QPSK(10), real tiered ranging "
               "codes) — fixed 61.38 MHz / sc8, looped buffer, optional power-preserving "
               "digital passband filter. Level is set in dBm via the unit's calibration; "
               "uncalibrated it runs on a relative gain. Authorised, shielded setups only.")
        .choice("-Band", "--band", options=["E5a", "E5b"], default="E5a",
                help="Which E5 sideband to transmit — sets the carrier AND codes. "
                     "E5a → 1176.45 MHz, E5b → 1207.14 MHz. Fixed per run.")
        .number("-Power", "--power", unit="dBm",
                **power_map().power_field_kwargs(), required=False, live=True,
                help="ABSOLUTE power at the delivered plane (dBm). Maps through the unit's "
                     "calibration and snaps to its achievable grid; ignored if --gain is "
                     "given. Live.")
        .number("-Gain", "--gain", unit="dB", min=0, max=HW_MAX_GAIN_DB,
                required=False, live=True,
                help="RELATIVE power: the SDR's raw TX gain (dB) directly, bypassing the dBm "
                     "calibration. When given, overrides --power. Live.")
        .integer("-SVID", "--svid", min=1, max=50, default=1,
                 help="Galileo SVID / primary-code number (1..50; operational 1..36). "
                      "Fixed per run.")
        .choice("-Filter", "--filter", options=["off", "on"], default="off",
                required=False, live=True,
                help="Digital passband filter on the looped buffer (unity passband gain, so "
                     "it preserves what it passes). Live.")
        .integer("-Sidelobes", "--sidelobes", min=0, max=MAX_SIDELOBES, default=1,
                 presets=SIDELOBE_PRESETS, required=False, live=True,
                 help="Passband width, as the number of sidelobes KEPT beside the main lobe: "
                      "a ±(n+1)·10.23 MHz band. Live (rebuilds the filtered loop).")
        .number("-Transition", "--transition", unit="MHz", min=0.1, max=8.0, default=1.0,
                required=False, live=True,
                help="Filter skirt transition width beyond the passband edge (MHz) — the "
                     "steepness knob. Live (rebuilds the filtered loop).")
        .choice("-RF", "--rf", options=["on", "off"], default="on", required=False, live=True,
                help="RF output on/off. OFF mutes the gain AND baseband amplitude to 0; ON "
                     "restores them. Live.")
    )


# ── Entry point ─────────────────────────────────────────────────────────────────

def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return _self_test()

    import atexit
    import shutil
    import tempfile

    script = build_script()
    args = script.parse()
    band = args.band
    center_freq_hz = BANDS[band]["freq"]

    if args.svid not in E5AQ_SEC:            # 1..50 guard (schema already bounds it)
        print(f"SVID {args.svid} out of range 1..50", file=sys.stderr)
        return 2

    pmap = power_map()
    amplitude = pmap.amplitude

    # Gain precedence: explicit --gain (raw) > calibrated --power > refuse (uncalibrated).
    gain_cal = getattr(args, "gain", None)
    if gain_cal is not None:
        gain_db = float(gain_cal)
    elif pmap.has_absolute:
        gain_db = pmap.gain_for_power(args.power, freq=center_freq_hz)
    else:
        _fb = os.environ.get("SDR_CAL_FALLBACK_GAIN")
        if _fb is None:
            print("error: this signal is not calibrated on this unit — absolute --power (dBm) "
                  "has no meaning here; set a relative gain (the client does this for you).",
                  file=sys.stderr)
            return 2
        gain_db = max(0.0, min(HW_MAX_GAIN_DB, float(_fb)))

    base_iq, nsamp, nper = build_iq_buffer(band, args.svid)

    shm = "/dev/shm" if os.path.isdir("/dev/shm") else None
    tmpdir = tempfile.mkdtemp(prefix="gal_e5_", dir=shm)
    atexit.register(lambda: shutil.rmtree(tmpdir, ignore_errors=True))

    def write_buffer(iq) -> str:
        fd, path = tempfile.mkstemp(suffix=".fc32", dir=tmpdir)
        os.close(fd)
        iq.tofile(path)
        return path

    shape = {"on": getattr(args, "filter", "off") == "on",
             "sidelobes": int(getattr(args, "sidelobes", 1) or 0),
             "trans_hz": float(getattr(args, "transition", 1.0) or 1.0) * 1e6}

    def make_current():
        if not shape["on"]:
            return base_iq, {"on": False}
        filtered, taps, fp = filter_buffer(base_iq, shape["sidelobes"], shape["trans_hz"])
        return filtered, {"on": True, "taps": taps, "edge_hz": fp,
                          "trans_hz": shape["trans_hz"]}

    iq0, finfo = make_current()
    box = {"file": write_buffer(iq0)}

    tb = _build_top_block(box["file"], center_freq_hz, gain_db, amplitude)

    def regenerate():
        iq, info = make_current()
        new_file = write_buffer(iq)
        tb.swap_file(new_file)
        old, box["file"] = box["file"], new_file
        try:
            os.unlink(old)
        except OSError:
            pass
        return info

    state = {"rf_on": getattr(args, "rf", "on") == "on", "gain": gain_db}
    if not state["rf_on"]:
        tb.set_gain(0.0)
        tb.set_amplitude(0.0)

    def _fmt_band(info):
        if not info.get("on"):
            return "off (full signal)"
        return (f"on — passband ±{info['edge_hz']/1e6:.2f} MHz, "
                f"{info['trans_hz']/1e6:g} MHz transition, {info['taps']} taps")

    conf = BANDS[band]
    print("── Galileo E5 TX ───────────────────────────────────────────")
    print(f"  band           : {band}  ({conf['data']} data / {conf['pilot']} pilot)")
    print(f"  SVID           : {args.svid}")
    print(f"  carrier        : {center_freq_hz/1e6:.3f} MHz")
    print(f"  sample rate    : {tb.actual_samp_rate()/1e6:.6f} MHz (fixed, 1:1 master clock)")
    print(f"  chip rate      : 10.23 Mcps QPSK (~20.46 MHz null-to-null)")
    print(f"  buffer         : {nsamp} samples ({nper}×100 ms, {nsamp*8/1e6:.1f} MB)")
    if pmap.has_absolute:
        print(f"  power (target) : {args.power:g} dBm  ({pmap.label})")
        print(f"  power (achieved on grid): "
              f"{pmap.power_for_gain(gain_db, freq=center_freq_hz):.2f} dBm")
    print(f"  → gain         : {gain_db:.2f} dB (max {pmap.max_gain_db:g}), amplitude {amplitude:g}")
    print(f"  calibration    : {pmap.describe()}")
    if pmap.warning:
        print(f"  ⚠ CALIBRATION  : {pmap.warning}")
    if gain_cal is not None:
        print("  ⚠ CALIBRATION  : raw --gain knob active — overrides --power")
    print(f"  filter         : {_fmt_band(finfo)}")
    print(f"  otw            : {OTW_FORMAT}")
    print(f"  RF             : {'ON' if state['rf_on'] else 'OFF (muted)'}")
    print("────────────────────────────────────────────────────────────")
    sys.stdout.flush()

    ctrl = script.live_control(args)

    def apply_change(name, value):
        if name == "power" and pmap.has_absolute:
            state["gain"] = pmap.gain_for_power(float(value), freq=center_freq_hz)
            if state["rf_on"]:
                tb.set_gain(state["gain"])
            ctrl.report("power", round(pmap.power_for_gain(state["gain"], freq=center_freq_hz), 2))
        elif name == "gain":
            state["gain"] = max(0.0, min(HW_MAX_GAIN_DB, float(value)))
            if state["rf_on"]:
                tb.set_gain(state["gain"])
            ctrl.report("gain", round(state["gain"], 2))
        elif name == "rf":
            on = str(value).strip().lower() in ("on", "1", "true", "yes")
            state["rf_on"] = on
            if on:
                tb.set_amplitude(amplitude)
                tb.set_gain(state["gain"])
            else:
                tb.set_gain(0.0)
                tb.set_amplitude(0.0)
            ctrl.report("rf", "on" if on else "off")
        elif name in ("filter", "sidelobes", "transition"):
            if name == "filter":
                shape["on"] = str(value).strip().lower() in ("on", "1", "true", "yes")
            elif name == "sidelobes":
                shape["sidelobes"] = max(0, min(MAX_SIDELOBES, int(value)))
            else:
                shape["trans_hz"] = float(value) * 1e6
            regenerate()
            ctrl.report(name, value)

    stop = threading.Event()
    signal.signal(signal.SIGTERM, lambda *_: stop.set())
    signal.signal(signal.SIGINT, lambda *_: stop.set())

    tb.start()
    try:
        while not stop.is_set():
            for change in ctrl.drain():
                apply_change(change.name, change.value)
            time.sleep(0.1)
    finally:
        ctrl.close()
        tb.stop()
        tb.wait()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
